name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  
  format:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      -name: Validating format...
        run: |
          npm run lint
          npm run format
      - name: Check for formatting changes
        id: git_diff
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git diff --exit-code || echo "Changes detected" 

      - name: Commit and push changes if any
        if: steps.git_diff.outputs.changes_detected
        run: |
          git add .
          git commit -m "chore: auto-format code"
          git push origin HEAD:${{ github.ref }}

  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Building...
        run: |
          npm ci 
          npm run build
      - name: Testing...
        run: |
          npm ci 
          npm run test

  image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Building...
        run: |
          npm ci 
          npm run build
      - name: Creating service image...
        run: docker build .
